### ISSUE TITLE
nexia-api package not installing cleanly

### ISSUE THREAD

**Issue by eightpointacres** [rahulpilani/homebridge-nexia-thermostat-ts#14]
I am following the instructions, but I can't get past these errors:

pi@raspberrypi:~ $ sudo npm install -g @cdmnky/nexia-api 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@0.4.3: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 58 packages, and audited 59 packages in 7s

2 packages are looking for funding
  run `npm fund` for details

3 critical severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Can someone recommend a solution?  Also does this nexia-api package work with the new tranehome.com website, or is there a newer package that I need for that.  I have all the other info I need from that site.  Thanks in advance

**Comment by eightpointacres** [comment]
I got past this issue, the new URL is https://tranehome.com/phones for the apiroute variable, but I am still not able to get it to work, now getting errors like:
[1/9/2022, 11:39:22 AM] [Downstairs] Error getting raw data. Error = Response code 404 (Not Found)
(node:1522) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'scale' of undefined
    at /usr/local/lib/node_modules/homebridge-nexia-american-standard-thermostat-ts/src/accessory.ts:374:28
    at /usr/local/lib/node_modules/homebridge-nexia-american-standard-thermostat-ts/src/accessory.ts:258:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
[1/9/2022, 11:39:22 AM] [Downstairs] Error getting raw data. Error = Response code 404 (Not Found)
(node:1522) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mappedMode' of undefined
    at /usr/local/lib/node_modules/homebridge-nexia-american-standard-thermostat-ts/src/accessory.ts:298:28
    at /usr/local/lib/node_modules/homebridge-nexia-american-standard-thermostat-ts/src/accessory.ts:258:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Any idea what to look at next?  Where is the debug log written to?  How to enable this?
